---
schema:
  procedures: {}
  tables:
    enquiry:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - email
          match_type: ''
          name: enquiry_email_key
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        create_date:
          data_type: timestamp
          default_value: !!perl/ref
            =: now()
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: create_date
          order: 4
          size:
            - 0
        email:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: email
          order: 3
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        latitude:
          data_type: real
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: latitude
          order: 7
          size:
            - 0
        location:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: location
          order: 6
          size:
            - 0
        longitude:
          data_type: real
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: longitude
          order: 8
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 2
          size:
            - 0
        notify_new_courses:
          data_type: boolean
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: notify_new_courses
          order: 9
          size:
            - 0
        notify_tutors:
          data_type: boolean
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: notify_tutors
          order: 10
          size:
            - 0
        send_newsletter:
          data_type: boolean
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: send_newsletter
          order: 11
          size:
            - 0
        suspend_date:
          data_type: timestamp
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: suspend_date
          order: 5
          size:
            - 0
      indices:
        - fields:
            - suspend_date
          name: enquiry_suspend_date_idx
          options: []
          type: NORMAL
        - fields:
            - latitude
          name: enquiry_latitude_idx
          options: []
          type: NORMAL
        - fields:
            - longitude
          name: enquiry_longitude_idx
          options: []
          type: NORMAL
      name: enquiry
      options: []
      order: 1
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Enquiry
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11020
